web1/Models/article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace web1.Models
{
    public class article
    {
        public int articleID { get; set; }

        [Required(ErrorMessage = "Please enter content of article.")]
        [DataType(DataType.Html)]
        public string article_data { get; set; }
        
        [Required(ErrorMessage = "Please enter header of article.")]
        public string article_header { get; set; }

        [Required(ErrorMessage = "Please enter creation time of article.")]
        [DataType(DataType.DateTime)]
        public DateTime article_creation_time { get; set; }

        public virtual member member { get; set; }
        public virtual List<comment> comments { get; set; }
    }
}

web1/Models/category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace web1.Models
{
    public class category
    {
        public int categoryID { get; set; }

        [Required(ErrorMessage = "Please enter name of category.")]
        [StringLength(50, ErrorMessage = "Name can not be longer than 50 character")]
        public string category_name { get; set; }

        public virtual List<article> articles { get; set; }
    }
}

web1/Models/comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace web1.Models
{
    public class comment
    {
        public int commentID { get; set; }

        [Required(ErrorMessage = "Please enter content of comment.")]
        public string comment_data { get; set; }

        [Required(ErrorMessage = "Please enter creation time of comment.")]
        [DataType(DataType.DateTime)]
        public DateTime comment_creation_time { get; set; }

        public virtual article article { get; set; }
        public virtual member member { get; set; }
    }
}

web1/Models/member.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace web1.Models
{
    public class member
    {
        public int memberID { get; set; }

        [Required(ErrorMessage = "Please enter email address.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Please use a correct e-mail address.")]
        public string member_email { get; set; }

        [Required(ErrorMessage = "Please enter a password")]
        [StringLength(15, ErrorMessage = "Password can not be longer than 15 character")]
        public string member_password { get; set; }

        public virtual List<article> articles { get; set; }
        public virtual List<comment> comments { get; set; }
    }
}

web1/Models/web1Context.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace web1.Models
{
    public class web1Context : DbContext
    {
        public DbSet<category> categories { get; set; }
        public DbSet<article> articles { get; set; }
        public DbSet<member> members { get; set; }
        public DbSet<comment> commetns { get; set; }
    }
}

web1/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web1.Models;

namespace web1.Controllers
{
    public class ArticleController : Controller
    {
        // GET: Article
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowArticle(int id)
        {
            web1Context db = new web1Context();

            List<article> articles = db.articles.Where(s => s.articleID == id).ToList();

            return PartialView(articles);
        }

        public ActionResult ShowComments(int articleID)
        {
            web1Context db = new web1Context();

            List<comment> comments = db.commetns.Where(s => s.article.articleID == articleID).ToList();

            return PartialView(comments);

        }
    }
}

web1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web1.Models;

namespace web1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowArticles()
        {
            web1Context db = new web1Context();

            List<article> articles = db.articles.OrderByDescending(s => s.article_creation_time).ToList();

            return PartialView(articles);
        }
    }
}

web1/Views/Article/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

web1/Views/Article/ShowArticle.cshtml
@{
    ViewBag.Title = "ShowArticle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model List<web1.Models.article>

@{
    foreach (var article in Model)
    {
        <!--div style="border:1px solid black"-->
        <h2>
            @article.article_header
        </h2>
        @Html.Raw(article.article_data)
        <strong>
            Olusturma Tarihi: @article.article_creation_time
        </strong>
        <p>
            <strong>Yorumlar</strong>
        </p>
        <p>
            @Html.Action("ShowComments", "Article", new { articleID = article.articleID })
        </p>
    }
}

web1/Views/Article/ShowComments.cshtml
@model List<web1.Models.comment>

@{
    foreach (var comment in Model)
    {
        <div style="border:1px solid black"-->
            <h3>
                @comment.member.member_email
            </h3>
            <p> @comment.comment_data</p>
        </div>
    }
}

web1/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>Hello from our View Template!</p>

@Html.Action("ShowArticles")

web1/Views/Home/ShowArticles.cshtml
@model List<web1.Models.article>

@{ 
    <h2> Makaleler </h2>
    foreach( var article in Model)
    {
        <!--div style="border:1px solid black"-->
        <h2>
            @article.article_header
        </h2>
        @Html.Raw(article.article_data)
        <strong>
            Olusturma Tarihi: @article.article_creation_time
        </strong>
        <p>
        @Html.ActionLink(
            "Devamini Oku...", 
            "ShowArticle", 
            "Article",
            new { id = article.articleID },
            null
        )
        </p>
    }
}

web1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="~/Content/style.css" media="screen" />
</head>
<body>
    <div id="wrap">
        <div id="menu">
            <ul>
                <li><a href="">Ana Sayfa</a></li>
                <li><a href="">Hakkında</a></li>
                <li><a href="">İletişim</a></li>
            </ul>
        </div>
        <div id="top">
            <h2> <a>Blog</a></h2>
        </div>
        <div id="content">
            <div id="left">
                <div class="box">
                    <ul class="input-list style-1 clearfix">
                        <li><input type="text" placeholder="Kullanıcı Adı"></li>
                        <li><input type="text" placeholder="Şifre"></li>
                        <li><button>Giriş</button></li>
                        <li><button>Üye Ol</button></li>
                    </ul>
                </div>
            </div>
            <div id="middle">
                    @RenderBody()
            </div>
            <div id="right">
                <div class="box">
                    <h2>Kategoriler</h2>
                    <ul>
                        <li><a href="">Randomised words</a> <i>10 nov 06</i></li>
                        <li><a href="">Look even slightly believable</a> <i>8 nov 06</i></li>
                        <li><a href="">Suffered alteration in form</a> <i>7 nov 06</i></li>
                        <li><a href="">Embarrassing hidden</a> <i>5 nov 06</i></li>
                        <li><a href="">Passages of lorem ipsum</a> <i>3 nov 06</i></li>
                    </ul>
                </div>
            </div>
            <div id="clear"></div>
        </div>
        <div id="footer">
            <p>Copyright 2017 Mesih Veysi Kılınç</p>
        </div>
    </div>
</body>
</html>